### ISSUE TITLE
Web redirect options

### ISSUE THREAD

**Issue by aaronpk** [aaronpk/oauth-first-party-apps#16]
Two options for web redirect fallback:

* Should we return a PAR URI and the client starts the web flow with a PAR request URI? Scopes would have already been requested before this point.
* Should we return a device session and then start a new OAuth flow (either PAR or normal). Client would also request new scopes for this flow.

**Comment by PieterKas** [comment]
Aaron's suggestion - describe how it should be done, and then point out this is compatible with PAR.

**Comment by aaronpk** [comment]
Done in #38
