### ISSUE TITLE
`auth_session` DPoP binding

### ISSUE THREAD

**Issue by aaronpk** [aaronpk/oauth-first-party-apps#24]
Do we need to have a DPoP parameter to bind the device session value?

**Comment by aaronpk** [comment]
Without DPoP binding, device session values should be one-time use.

**Comment by PieterKas** [comment]
DPoP Section 4.2 defines the extension mechanism.

**Comment by aaronpk** [comment]
We can define a new parameter `ash` (auth session hash) to include the hash of the `auth_session` in the DPoP proof:

https://datatracker.ietf.org/doc/html/rfc9449#name-dpop-proof-jwt-syntax
