### ISSUE TITLE
First Party Native Apps in Browsers

### ISSUE THREAD

**Issue by PieterKas** [aaronpk/oauth-first-party-apps#29]
A participant at OSW suggested they would consider using the native apps spec in the browser. That is contrary to our recommendations in the spec, but opening an issue here to keep track of it until we understand more about that use case.

**Comment by gffletch** [comment]
Interesting, in that "native controls" are limited within a browser. My big concern is how to have high trust it's a 1st party app. Communications could be protected with DPoP to some extent. Hmm...

**Comment by gffletch** [comment]
I think the biggest issue for me with browsers is that we don't have any equivalent to an "OS App attestation". If the browser was willing to assert that the JS app was loaded from a particular domain and provides some sort of attestation as to the code it received (hash of loaded JS)... then maybe. There just are the same controls within the browser environment that there are for mobile applications.

**Comment by dteleguin** [comment]
Hi, OSW participant here :) Our main use case is reauthenticating the user of the SPA (step-up, transaction confirmation etc.) without leaving the context of the application, providing native experience at the same time. When using redirect-based flow for the same, the live data stream from the application will be interrupted. This includes (but is not limited to):
* market tickers;
* text messages;
* audio streams / voice calls;
* video feeds.

Iframes and popups could do the trick, but there are (at least) two problems here:
* auth server would generally be using a web technology different from the main app, and it could take significant effort to achieve a semblance of the native UX (if at all possible);
* we don't have a standard for inter-window (or frame) communication. Unfortunately,  [OAuth 2.0 Web Message Response Mode](https://datatracker.ietf.org/doc/draft-sakimura-oauth-wmrm/) didn't progress back in 2016.

**Comment by aaronpk** [comment]
We can expand the new SPA security considerations section to include: https://aaronpk.github.io/oauth-first-party-apps/draft-parecki-oauth-first-party-apps.html#name-single-page-applications

* Most of the time it's not worth the additional complexity of adding this to a SPA vs doing a full page redirect or popup window for the auth code flow
* (Steal some language around the first-party problem from section 9.1)
