### ISSUE TITLE
Add shelling out to the browser as a error code

### ISSUE THREAD

**Issue by PieterKas** [aaronpk/oauth-first-party-apps#30]
A question came up on how this would work. Demonstrating this scenario with the help of an example may be useful.

**Comment by aaronpk** [comment]
We should define a new error code that tells the client to launch a browser flow instead https://aaronpk.github.io/oauth-first-party-native-apps/draft-parecki-oauth-first-party-native-apps.html#section-5.2.2

**Comment by aaronpk** [comment]
Done in #38
