### ISSUE TITLE
Content Type

### ISSUE THREAD

**Issue by PieterKas** [aaronpk/oauth-first-party-apps#31]
One of the participants in the OSW workshop suggested adding a content type parameter to allow them to specify for example a JSON structure or some other data format to control the native app experience. We have been deliberately avoiding defining a new language or re-inventing HTML, but allowing implementors to return complex content types of their own definition may be worth considering if this is a common enough use case.

**Comment by aaronpk** [comment]
* Make it more clear in 5.2 that this spec expects the response to always be either the authorization code or an error https://aaronpk.github.io/oauth-first-party-native-apps/draft-parecki-oauth-first-party-native-apps.html#section-5.2
* Section 5.2.2 needs to make it clear that the authorization server has to define its own error codes https://aaronpk.github.io/oauth-first-party-native-apps/draft-parecki-oauth-first-party-native-apps.html#section-5.2.2
* Section 5.2.2 should explicitly allow more specific JSON content types `application/whatever+json`
