### ISSUE TITLE
Add security consideration discouraging use of this spec in SPAs

### ISSUE THREAD

**Issue by aaronpk** [aaronpk/oauth-first-party-apps#36]
tbd: "Due to the inability to securely attest to the first-partyness of a browser based application, it is NOT RECOMMENDED to use this application in a browser-based application."

**Comment by dteleguin** [comment]
Thinking out loud, would the hypothetic "SPA attestation" be possible in principle / make sense at all?

**Comment by aaronpk** [comment]
> Thinking out loud, would the hypothetic "SPA attestation" be possible in principle / make sense at all?

Yes, Chrome has a proposal for the "Web Integrity API", but it has received a lot of pushback:

https://github.com/RupertBenWiser/Web-Environment-Integrity/blob/main/explainer.md

Safari already shipped Private Access Tokens which are similar:

https://developer.apple.com/news/?id=huqjyh7k
