### ISSUE TITLE
random stringo 

### ISSUE THREAD

**Issue by bc-pi** [aaronpk/oauth-first-party-apps#44]
typo in https://www.ietf.org/archive/id/draft-parecki-oauth-first-party-apps-00.html#section-5.3-2 
"for example by using a random stringo using a JWE if the AS is not" 
should probably be 
"for example by using a random string or using a JWE if the AS is not"

**Comment by aaronpk** [comment]
thanks, that was fixed in https://github.com/aaronpk/oauth-first-party-apps/pull/42

**Comment by bc-pi** [comment]
glad I could help :/
