### ISSUE TITLE
DPoP binding of auth_session

### ISSUE THREAD

**Issue by yaronf** [aaronpk/oauth-first-party-apps#84]
Since RFC 9449 does not specify how "additional" parameters can be bound, please say explicitly that (presumably) this is a claim within the DPoP proof JWT named "auth_session".

**Comment by aaronpk** [comment]
It is not a new claim in the DPoP proof, because that would imply the binding happens from the client, not the AS. Brian's suggestion was to require the AS to do the binding, in which case it's internal and not part of the spec.

**Comment by yaronf** [comment]
So can you please fine tune the language in 9.6.1. At least this reader understands the word "binding" when used in this context as cryptographic binding, and this is obviously not what you want. Maybe use "associate" instead.

**Comment by yaronf** [comment]
Fixed by #95.
